sudo: false
language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g Financial-Times/origami-build-tools#node-0.10
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm test
